name: form_fields_example
description: Example application demonstrating FormFields package usage.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  form_fields:
    path: ../
  logger: any
  go_router: any
  shared_preferences: any
  provider: any
  json_annotation: any
  dio: any
  permission_handler: any
  camera: any
  google_fonts: any
  file_picker: ^11.0.2
  workmanager: any
  path_provider: any
  path: any
  geolocator: any
  flutter_map: any
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: any
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - migrations/
