include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "example/build/**"
    - "**/build/**"
    - "**/SourcePackages/**"
    - ".dart_tool/**"
    - "**/.dart_tool/**"
