name: form_fields
description: A comprehensive and reusable Flutter form field widget with support
  for multiple input types including text, email, phone, password, date, time,
  and more.
version: 1.0.0
homepage: https://github.com/renoldi/form_fields
repository: https://github.com/renoldi/form_fields
issue_tracker: https://github.com/renoldi/form_fields/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio: any
  flutter:
    sdk: flutter
  intl: any
  json_annotation: any
  logger: any
  provider: any
  cunning_document_scanner: any
  image_picker: any
  permission_handler: any

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  json_serializable: any

flutter: null
