// ============================================================================
// BUILD SETTINGS - AUTO-GENERATED FILE
// ============================================================================
// 
// ⚠️ DO NOT EDIT THIS FILE MANUALLY!
// 
// This file is automatically generated by:
//   dart run tool/configure_build.dart
//
// Last generated: 2026-03-02T10:55:59.229271
// Environment: production
//
// To change these settings, run the configuration tool:
//   dart run tool/configure_build.dart --env=debug|beta|production [options]
//
// For more information, see: HOW_TO_USE.md
// ============================================================================

/// Build settings for DEBUG environment
class DebugBuildSettings {
  static const String androidNamespace = 'com.example.form_fields_example.debug';
  static const int androidCompileSdk = 36;
  static const String ndkVersion = '27.0.12077973';
  static const int androidMinSdk = 21;
  static const int androidTargetSdk = 36;
  static const int versionCode = 1;
  static const String versionName = '1.0.0';
  static const String androidMapsApiKey = 'DEBUG_GOOGLE_MAPS_API_KEY';
  static const String iosMapsApiKey = 'DEBUG_GOOGLE_MAPS_API_KEY';
  static const String iosMinimumDeploymentTarget = '12.0';
  static const String macosMinimumDeploymentTarget = '10.15';
  static const int windowsMinimumVersion = 10;
  static const String webDomain = 'localhost:8080';
  
  static const List<String> androidPermissions = [
    'android.permission.INTERNET',
    'android.permission.ACCESS_NETWORK_STATE',
    'android.permission.CHANGE_NETWORK_STATE',
    'android.permission.ACCESS_FINE_LOCATION',
    'android.permission.ACCESS_COARSE_LOCATION',
    'android.permission.CAMERA',
    'android.permission.READ_MEDIA_IMAGES',
    'android.permission.READ_EXTERNAL_STORAGE',
    'android.permission.POST_NOTIFICATIONS',
  ];
}

/// Build settings for BETA environment
class BetaBuildSettings {
  static const String androidNamespace = 'com.example.form_fields_example.beta';
  static const int androidCompileSdk = 36;
  static const String ndkVersion = '27.0.12077973';
  static const int androidMinSdk = 21;
  static const int androidTargetSdk = 36;
  static const int versionCode = 1;
  static const String versionName = '1.0.0';
  static const String androidMapsApiKey = 'BETA_GOOGLE_MAPS_API_KEY';
  static const String iosMapsApiKey = 'BETA_GOOGLE_MAPS_API_KEY';
  static const String iosMinimumDeploymentTarget = '12.0';
  static const String macosMinimumDeploymentTarget = '10.15';
  static const int windowsMinimumVersion = 10;
  static const String webDomain = 'beta.example.com';
  
  static const List<String> androidPermissions = [
    'android.permission.INTERNET',
    'android.permission.ACCESS_NETWORK_STATE',
    'android.permission.CHANGE_NETWORK_STATE',
    'android.permission.ACCESS_FINE_LOCATION',
    'android.permission.ACCESS_COARSE_LOCATION',
    'android.permission.CAMERA',
    'android.permission.READ_MEDIA_IMAGES',
    'android.permission.READ_EXTERNAL_STORAGE',
    'android.permission.POST_NOTIFICATIONS',
  ];
}

/// Build settings for PRODUCTION environment
class ProductionBuildSettings {
  static const String androidNamespace = 'com.example.form_fields_example';
  static const int androidCompileSdk = 36;
  static const String ndkVersion = '27.0.12077973';
  static const int androidMinSdk = 21;
  static const int androidTargetSdk = 36;
  static const int versionCode = 1;
  static const String versionName = '1.0.0';
  static const String androidMapsApiKey = 'PRODUCTION_GOOGLE_MAPS_API_KEY';
  static const String iosMapsApiKey = 'PRODUCTION_GOOGLE_MAPS_API_KEY';
  static const String iosMinimumDeploymentTarget = '12.0';
  static const String macosMinimumDeploymentTarget = '10.15';
  static const int windowsMinimumVersion = 10;
  static const String webDomain = 'example.com';
  
  static const List<String> androidPermissions = [
    'android.permission.INTERNET',
    'android.permission.ACCESS_NETWORK_STATE',
    'android.permission.CHANGE_NETWORK_STATE',
    'android.permission.ACCESS_FINE_LOCATION',
    'android.permission.ACCESS_COARSE_LOCATION',
    'android.permission.CAMERA',
    'android.permission.READ_MEDIA_IMAGES',
    'android.permission.READ_EXTERNAL_STORAGE',
    'android.permission.POST_NOTIFICATIONS',
  ];
}
